# Generated by Django 2.2.4 on 2019-08-30 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RecipesAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.TextField(max_length=300)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='RecipesAPI.Recipes_model')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='RecipesAPI.Recipes_model')),
            ],
        ),
    ]
